#!/usr/bin/env bash

# Prepend pwd if relative path
FILENAME=$1
[[ $FILENAME != /* ]] && FILENAME="$PWD/$FILENAME"

# Build command (default is vim)
COMMAND='no_command_parsed'
[ ! -z $2 ] && COMMAND="$2 $FILENAME"
[ -z $2 ] && COMMAND="vim $FILENAME"

# Add read to cat command so that the terminal doesn't close immediately
[[ $2 == "cat" ]] && COMMAND="$COMMAND; read"

# Add shell to ls command so that the terminal doesn't close and we can browse further
[[ $2 == ls* ]] && COMMAND="$COMMAND; $SHELL"

echo $COMMAND

# Open vim in new fullscreen terminal
gnome-terminal --maximize -- /usr/bin/bash -c "$COMMAND"
