#!/usr/bin/env bash

# Prepend pwd if relative path
FILENAME=$1
[[ $FILENAME != /* ]] && FILENAME="$PWD/$FILENAME"

# Build command (default is vim)
COMMAND='no_command_parsed'
[ ! -z $2 ] && COMMAND="$2 $FILENAME ; read"
[ -z $2 ] && COMMAND="vim $FILENAME" 

echo $COMMAND

# Open vim in new fullscreen terminal
gnome-terminal --maximize -- /usr/bin/bash -c "$COMMAND"
